# Generated by Django 3.2 on 2021-04-28 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='date_of_dest',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='friendship',
            name='date_of_send',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
