# Generated by Django 3.2 on 2021-04-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='permissions',
            field=models.IntegerField(default=0, verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
