# Generated by Django 3.2 on 2021-04-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_quote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Киноцитата', 'verbose_name_plural': 'Киноцитаты'},
        ),
        migrations.AddField(
            model_name='quote',
            name='hero',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кто сказал'),
        ),
    ]
