# Generated by Django 3.2 on 2021-04-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20210501_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='short_description',
            field=models.TextField(default='', verbose_name='Краткое описание'),
        ),
    ]
