# Generated by Django 3.2 on 2021-05-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20210502_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
